import type { Ficha } from "./schema";

/**
 * LA PIRÁMIDE (Sprint 006) — las fichas de actividad del documento de la mamá (/mirada).
 *
 * 56 fichas por los seis grupos de la pirámide, que se trabajan todos a la vez: imitación 12 ·
 * atención conjunta 7 · juego 13 (los tres de prioridad ahora) · señalar 4 · intención
 * comunicativa 10 · comprender 10. Salen de ejecutar el mapa de las 74 aprobado en
 * G-Investigación: 19 del documento anterior quedan (cambian de forma) · 4 se unen en «Con el
 * hermano: la misma rutina» · 1 se une a «El frasco que no abre» · 2 de la app quedan · 7 nacen
 * de fusionar cápsulas de la app · 28 son nuevas, de la investigación privada del S6 · 11 caen
 * del documento (siguen intactas en la app: ver CAEN_DEL_DOCUMENTO).
 *
 * Cada ficha en instrucción directa: Ten a la mano · Haz · Tu línea · Espera ver · Funcionó si ·
 * Si no pasa. Personalizadas con lo que al niño ya le gusta (marchar, «corre que te atrapo», las
 * cosquillas con su sonido, señalar y decir «tú», «hola» y «chao», las vocales). Solo
 * comportamiento observable; el gate de sensibilidad lo vigila.
 *
 * (Solo `import type` desde ./schema: el generador corre con Node quitando tipos.)
 */
export const FICHAS: Ficha[] = [
  // ════════════════ IMITACIÓN (prioridad ahora) ════════════════
  {
    id: "dos-juguetes-iguales",
    grupo: "imitacion",
    prioridad: "alta",
    tecnica: "lo-copio",
    titulo: "Dos iguales: tú lo copias a él",
    tenALaMano: [
      "Dos juguetes iguales que ya le gusten (nada nuevo el primer día): dos carros, dos tambores o dos cucharas de palo.",
    ],
    haz: [
      "Pon un juguete frente a él y el gemelo frente a ti, y siéntate de frente, a su altura.",
      "Copia en el momento todo lo que haga con el suyo: si golpea, golpeas; si lo tira, lo tiras; si hace un sonido, lo haces.",
      "No le pidas nada, no le preguntes nada, no le enseñes nada.",
      "Cuando te mire, sonríe y sigue copiando.",
      "Para antes de que se aburra.",
    ],
    tuLinea: "Sin palabras al principio. Cuando te mire: «¡Igual que tú!»",
    esperaVer:
      "Primero mira lo que haces con tu juguete; luego te mira a ti. Puede repetir algo mirándote, para ver si lo copias otra vez, y acercarse.",
    funcionoSi:
      "hace algo con su juguete mirándote para ver si lo copias, o cambia de acción y espera tu copia.",
    siNoPasa:
      "Copia más grande y más rápido, con el juguete que él eligió. Deja un solo par de juguetes. Y prueba en otro momento del día.",
    duracion: "3–5 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "I1",
    origen: { de: "mirada", refs: ["mirada:dos-juguetes-iguales", "anexo:B-A1"] },
    fuente: "Sanefuji, 2013, Infant Ment Health J · Contaldo, 2016, Front Psychol",
  },
  {
    id: "el-prueba-si-lo-copias",
    grupo: "imitacion",
    prioridad: "alta",
    tecnica: "lo-copio",
    titulo: "Él prueba si lo copias",
    tenALaMano: ["Los dos juguetes iguales de siempre."],
    haz: [
      "Juega a copiarlo como en «Dos iguales».",
      "Fíjate en el momento en que él hace algo y voltea a verte.",
      "Cópialo en ese mismo segundo, más grande que él y con cara de fiesta.",
      "Si cambia de juguete o de movimiento, cambia tú también.",
    ],
    tuLinea: "«¿Y ahora?… ¡Igualito!»",
    esperaVer:
      "Que haga un movimiento y se quede mirándote para ver si lo repites. Es la primera vez que la mirada la pone él.",
    funcionoSi: "repite algo o cambia de movimiento y se queda mirándote hasta que lo copias.",
    siNoPasa:
      "No busques la prueba: sigue copiándolo sin esperar nada. Si voltea a verte y no pasa nada, deja de probar; por eso, cópialo siempre.",
    duracion: "3–5 min",
    momentos: ["juego"],
    conQuien: "mama",
    origen: { de: "mirada", refs: ["mirada:el-prueba-si-lo-copias"] },
    fuente: "Escalona, 2002 · Field, 2013, Infant Child Dev",
  },
  {
    id: "sigo-su-ritmo",
    grupo: "imitacion",
    prioridad: "alta",
    tecnica: "canto-a-su-ritmo",
    titulo: "Sigo su ritmo: él golpea, yo golpeo",
    tenALaMano: ["Nada; si quieres, una olla y una cuchara para ti."],
    haz: [
      "Cuando lo veas golpear, marchar o hacer un sonido que se repite, ponte de frente, a su altura.",
      "Sigue su ritmo con las manos, con la olla o con la voz, a su velocidad.",
      "Si acelera, aceleras; si para, paras.",
      "Después de un rato igual a él, cambia una sola cosa (un golpe más fuerte, un paso de gigante) y vuelve a seguirlo.",
    ],
    tuLinea: "«Pum, pum, pum… ¡así, así!»",
    esperaVer:
      "Que voltee a ver de dónde sale el eco de su ritmo, y que te mire cuando cambias algo.",
    funcionoSi:
      "te mira cuando lo sigues o cuando cambias algo, y el juego termina porque él lo decide, no porque se fue.",
    siNoPasa:
      "Estabas marcando tú el ritmo: vuelve a seguirlo exacto, ni más rápido ni más lento que él. Y nada de música grabada.",
    duracion: "2–3 min",
    momentos: ["juego", "comida"],
    conQuien: "mama",
    progresion: "I1",
    origen: { de: "mirada", refs: ["mirada:sigo-su-ritmo", "anexo:D-A3"] },
    fuente: "Kim, 2008 · Gulsrud, 2016, J Child Psychol Psychiatry",
  },
  {
    id: "una-estrofa-mas",
    grupo: "imitacion",
    prioridad: "alta",
    tecnica: "canto-a-su-ritmo",
    titulo: "Canción con gestos: una estrofa más cada semana",
    tenALaMano: [
      "Una canción con gestos que ya conozca: «este dedito», «la araña» o «abre y cierra».",
    ],
    haz: [
      "Siéntate de frente, a su altura.",
      "Canta solo la primera estrofa, con los gestos grandes.",
      "Antes de cada gesto, para un instante y espera a que lo haga él o te mire.",
      "Repite esa estrofa unas veces y termina.",
      "La semana siguiente, agrega la segunda estrofa; no antes.",
    ],
    tuLinea: "«Este dedito compró un huevito…» (pausa, manos listas) «…¡y este gordito se lo comió!»",
    esperaVer:
      "Que haga el gesto contigo o justo después de ti, y que te mire en la pausa para saber cuándo sigue.",
    funcionoSi: "hace un gesto de la canción cuando tú lo haces, o lo hace él primero en la pausa.",
    siNoPasa:
      "Una estrofa, una sola vez, y lo dejas. Nunca le muevas tú las manos para hacer el gesto.",
    duracion: "2–3 min",
    momentos: ["juego", "dormir"],
    conQuien: "mama",
    progresion: "I3",
    origen: { de: "mirada", refs: ["mirada:una-estrofa-mas"] },
    fuente: "Kim, 2009 · Stephens, 2008",
  },
  {
    id: "ahora-yo-ahora-tu",
    grupo: "imitacion",
    prioridad: "alta",
    tecnica: "ahora-yo-ahora-tu",
    titulo: "Ahora yo, ahora tú: una acción nueva con el juguete",
    tenALaMano: [
      "Los dos juguetes iguales.",
      "Tres o cuatro acciones sencillas pensadas de antemano: rodar, golpear, meter, tapar, sacudir.",
    ],
    haz: [
      "Empieza copiándolo a él un rato, y di en una o dos palabras lo que hace: «golpea», «rueda».",
      "De vez en cuando, haz tú una acción nueva con tu juguete, bien visible, con una palabra —«¡a rodar!»— y espera.",
      "Si la copia, celébralo con la voz y la cara, y vuelve a copiarlo tú a él.",
      "Si no la copia después de verla unas veces, llévale las manos con suavidad, una sola vez, y celébralo igual.",
      "La mayor parte del rato eres tú quien lo copia; la acción nueva es de vez en cuando.",
    ],
    tuLinea: "«¡Ahora yo!… ¡ahora tú!» — igual que en las cosquillas.",
    esperaVer:
      "Primero copia con tus manos guiando; después, cuando le muestras; con el tiempo, cosas que te vio hacer sin que se las mostraras a propósito.",
    funcionoSi:
      "repite con su juguete la acción que tú acabas de hacer, sin que le lleves las manos, aunque sea a medias.",
    siNoPasa:
      "Una acción más fácil (solo una parte del movimiento), o la que él ya hace con el cuerpo pasada al juguete. Menos acciones nuevas y más copiarlo tú. Si retira las manos, suéltalo.",
    duracion: "5–10 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "I3",
    origen: { de: "nueva", refs: ["anexo:B-A2", "anexo:D-A10"] },
    fuente: "Ingersoll, 2010 · Ingersoll, 2012",
  },
  {
    id: "eco-de-voz",
    grupo: "imitacion",
    prioridad: "alta",
    tecnica: "lo-copio",
    titulo: "Eco de voz: le devuelves su sonido",
    tenALaMano: ["Nada. Los momentos en que él suena solo: en el baño, en el carro, al despertar."],
    haz: [
      "Cuando haga un sonido o una vocal, repítelo igual y enseguida, mirándolo: mismo tono, mismo largo.",
      "Espera en silencio a que vuelva a sonar.",
      "Si suena, vuelve a copiarlo: eso ya es un turno.",
      "Después de varios turnos, cambia un poquito tu eco (más largo, otra vocal) y espera.",
      "Para cuando él pare.",
    ],
    tuLinea: "Él: «aaa». Tú, igualito: «aaa»… y esperas.",
    esperaVer:
      "Que suene después de tu eco y espere el tuyo: él, tú, él, tú. Luego, que copie tus pequeños cambios.",
    funcionoSi: "después de tu eco vuelve a sonar y se queda esperando el tuyo: ya hay ida y vuelta.",
    siNoPasa:
      "No cambies nada: solo el eco exacto, hasta que el ida y vuelta exista. Hazlo cuando más suena, nunca cuando está metido en un juguete.",
    duracion: "1–3 min",
    momentos: ["baño", "calle", "transiciones"],
    conQuien: "mama",
    origen: { de: "nueva", refs: ["anexo:B-A3", "habla:sonidos-habla-como-el"] },
    fuente: "Ishizuka, 2016 · Gazdag, 2000, J Early Interv",
  },
  {
    id: "marchar-con-algo-en-la-mano",
    grupo: "imitacion",
    prioridad: "alta",
    tecnica: "ahora-yo-ahora-tu",
    titulo: "Marchar con algo en la mano",
    tenALaMano: [
      "Dos cucharas de palo, o dos botellas con arroz que suenen: la suya, a su alcance, sin dársela.",
      "Dos ollas para golpear al final.",
    ],
    haz: [
      "Arranca la marcha de siempre, sin nada en las manos.",
      "En la segunda vuelta, marcha con tu cuchara arriba y abajo, al ritmo.",
      "Si la toma, copia lo que haga con ella.",
      "Cambia tú la acción con la cuchara (golpear la olla, apuntar al techo, dar vueltas) y espera.",
      "Si te copia, celébralo y vuelvan a marchar.",
    ],
    tuLinea: "«¡Marcha, marcha… y pum!»",
    esperaVer:
      "Que tome la cuchara y la mueva como movía los brazos, y que copie el golpe en la olla.",
    funcionoSi: "hace con su cuchara lo que tú hiciste con la tuya, no solo la lleva en la mano.",
    siNoPasa:
      "Deja la cuchara a la vista varias vueltas sin insistir. Usa algo que suene: el sonido es la gracia. Y sigue marchando tú, exagerado.",
    duracion: "3–5 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "I3",
    origen: { de: "nueva", refs: ["anexo:B-A4", "anexo:F-F5"] },
    fuente: "Stone, 1997 · Ingersoll, 2010",
  },
  {
    id: "cosquillas-con-sonido",
    grupo: "imitacion",
    prioridad: "alta",
    tecnica: "pausa-antes-de-lo-mejor",
    titulo: "Cosquillas con sonido, sonido sin cosquillas",
    tenALaMano: ["Nada: el juego de cosquillas, con su sonido de siempre."],
    haz: [
      "Juega cosquillas como siempre, con el sonido del juego.",
      "Cuando él haga el sonido, cópialo igualito antes de la siguiente ronda.",
      "Haz el sonido sin cosquillas: manos quietas, cara de espera.",
      "Si él hace el sonido, llegan las cosquillas: su sonido pide el juego.",
      "Cuando él te haga cosquillas a ti, haz tú el sonido y espera a que lo repita.",
    ],
    tuLinea: "Su sonido, tal cual… (manos quietas, cara de espera)… ¡y cosquillas!",
    esperaVer:
      "Que haga su sonido para pedir la ronda, y que lo haga en los dos papeles: cuando las recibe y cuando las da.",
    funcionoSi: "hace el sonido cuando tú lo haces sin cosquillas, o lo usa para pedirlas.",
    siNoPasa:
      "La espera, cortita: tres segundos y sigues. Vuelve a una ronda completa y lo intentas otra vez. Copia su sonido más veces antes de esperar.",
    duracion: "2–3 min",
    momentos: ["juego", "vestirse"],
    conQuien: "mama",
    progresion: "I3",
    origen: { de: "nueva", refs: ["anexo:B-A5"] },
    fuente: "Ishizuka, 2016 · Halle, 1981, J Appl Behav Anal",
  },
  {
    id: "gestos-que-dicen-algo",
    grupo: "imitacion",
    prioridad: "alta",
    tecnica: "ahora-yo-ahora-tu",
    titulo: "Gestos que dicen algo",
    tenALaMano: [
      "Cuatro o cinco gestos fijos, siempre con la misma palabra: «grande» (brazos abiertos), «se cayó» (manos abajo), «rápido» (la mano que corre), «arriba», «no hay» (palmas arriba).",
    ],
    haz: [
      "Mientras juegan, cada vez que pase algo, haz el gesto con su palabra: «¡se cayó!» con las manos abajo.",
      "Usa siempre el mismo gesto con la misma palabra.",
      "Después del gesto, espera un instante.",
      "Si lo copia, di la palabra otra vez y sigue jugando; si no, sigue igual: el gesto vuelve a aparecer solo.",
    ],
    tuLinea: "«¡Se cayó!» (manos abajo) · «¡Chao, carro!» (la mano de chao)",
    esperaVer:
      "Que copie el gesto, y más adelante que lo haga él antes que tú cuando pasa lo mismo.",
    funcionoSi:
      "hace uno de los gestos por su cuenta cuando pasa lo que el gesto dice (se cae el carro y baja las manos), con o sin palabra.",
    siNoPasa:
      "Solo dos gestos, más grandes, pegados a lo que más le gusta: «¡rápido!» en la persecución. Nunca se los pidas.",
    duracion: "2–5 min",
    momentos: ["juego", "transiciones"],
    conQuien: "mama",
    progresion: "I4",
    origen: { de: "nueva", refs: ["anexo:B-A6"] },
    fuente: "Ingersoll, 2010, J Speech Lang Hear Res · Stone, 1997",
  },
  {
    id: "sonidos-de-las-cosas",
    grupo: "imitacion",
    prioridad: "alta",
    tecnica: "ahora-yo-ahora-tu",
    titulo: "Sonidos de las cosas: el avión hace «uuuh»",
    tenALaMano: [
      "Tres cosas con su sonido de siempre: el avión («uuuh»), el carro («brrum»), el tambor («pum»). Dos de cada una, si se puede.",
    ],
    haz: [
      "Juega a copiarlo con los juguetes, como en «Dos iguales».",
      "Cada vez que muevas el tuyo, ponle su sonido, siempre el mismo.",
      "Cuando él mueva el suyo, ponle tú el sonido.",
      "Haz la acción con su sonido y espera.",
      "Si él hace solo el sonido o solo la acción, celébralo y completa tú la otra mitad.",
    ],
    tuLinea: "«El avión… ¡uuuuh!»",
    esperaVer: "Primero la acción sin sonido, o el sonido sin acción; después, los dos juntos.",
    funcionoSi: "hace el sonido mientras mueve el juguete, o hace el sonido para que tú muevas el tuyo.",
    siNoPasa:
      "Empieza por el sonido más parecido a los que ya hace: la «uuuh» larga del avión antes que el «brrum». Un solo juguete con su sonido por semana.",
    duracion: "3–5 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "I3",
    origen: {
      de: "nueva",
      refs: ["anexo:B-A7", "habla:sonidos-ponle-sonido-al-mundo", "habla:sonidos-su-sonido-tu-palabra"],
    },
    fuente: "Van de Vyver, 2026, J Speech Lang Hear Res · Ishizuka, 2021",
  },
  {
    id: "espejo-por-turnos",
    grupo: "imitacion",
    prioridad: "alta",
    tecnica: "ahora-yo-ahora-tu",
    titulo: "Espejo por turnos: el ida y vuelta que dura",
    tenALaMano: ["Los dos juguetes iguales, o nada: también sirve en la persecución."],
    haz: [
      "Él hace algo y tú lo copias.",
      "Haz tú un cambio pequeñito de lo mismo (más fuerte, más lento, al revés) y espera.",
      "Si copia tu cambio, cópialo otra vez agregando otro cambio mínimo.",
      "Cuando él cambie de acción, vuelves a copiarlo a él.",
      "Nombra cada turno siempre igual: «ahora yo… ahora tú».",
    ],
    tuLinea: "«Ahora yo… ahora tú.»",
    esperaVer:
      "Cadenas cada vez más largas alrededor de la misma acción, con él mirándote entre un turno y el otro.",
    funcionoSi:
      "el ida y vuelta sigue varias veces seguidas sobre la misma acción, sin que le lleves las manos.",
    siNoPasa:
      "Cambios todavía más pequeños y turnos tuyos más cortos. Vuelve un rato a solo copiarlo. Empieza por la persecución: corre, para, mira; tú corres, paras, miras.",
    duracion: "3–5 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "I5",
    origen: { de: "nueva", refs: ["anexo:B-A8", "habla:sonidos-turnos-de-sonidos"] },
    fuente: "Field, 2013, Infant Child Dev · Ishizuka, 2016",
  },
  {
    id: "dos-pasos-y-lo-de-ayer",
    grupo: "imitacion",
    prioridad: "alta",
    tecnica: "ahora-yo-ahora-tu",
    titulo: "Dos pasos, y lo de ayer",
    tenALaMano: [
      "Cosas con dos pasos naturales: meter la pelota y tapar; llenar el vaso y vaciarlo; subir el muñeco al carro y empujar.",
      "Que «Ahora yo, ahora tú» ya salga con una acción; si no, empieza por esa ficha.",
    ],
    haz: [
      "Haz dos acciones seguidas con tu juguete, cada una con su palabra —«meto… ¡tapo!»— y espera.",
      "Si hace un paso, celébralo y haz tú el segundo; si hace los dos, celébralo en grande.",
      "Al día siguiente, deja las cosas a la vista sin mostrarle nada, y mira qué hace.",
      "Si repite la cadena de ayer, cópialo y ponle las palabras.",
    ],
    tuLinea: "«Meto… ¡y tapo!»",
    esperaVer: "Primero un paso; luego los dos; con el tiempo, la cadena de ayer sin que se la muestres.",
    funcionoSi:
      "hace los dos pasos en orden después de verte, o repite al día siguiente una cadena que solo vio el día anterior.",
    siNoPasa:
      "Vuelve a un solo paso. Que el segundo paso se oiga o se vea (tapar suena, vaciar se ve). Una cadena nueva por semana, no más.",
    duracion: "3–5 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "I6",
    origen: { de: "nueva", refs: ["anexo:B-A10"] },
    fuente: "Toth, 2006 · Van de Vyver, 2026, J Speech Lang Hear Res",
  },

  // ════════════════ ATENCIÓN CONJUNTA (prioridad ahora) ════════════════
  {
    id: "te-trae-el-otro-juguete",
    grupo: "atencion-conjunta",
    prioridad: "alta",
    tecnica: "lo-copio",
    titulo: "Te trae el otro juguete: arranca él",
    tenALaMano: ["Los dos juguetes iguales, en su sitio de siempre y a su alcance."],
    haz: [
      "Deja los dos juguetes a la vista y no arranques tú.",
      "Si él te trae el tuyo o empieza algo mirándote, juega a copiarlo como siempre.",
      "A mitad del juego, una sola vez, haz tú algo nuevo y espera con cara de «¿lo haces?».",
      "Si te copia, celébralo copiándolo tú de vuelta; si no, sigue copiándolo a él.",
    ],
    tuLinea: "«¡Ah, quieres que juguemos igual! Dale, tú primero.»",
    esperaVer:
      "Que un día te traiga el juguete o te busque para empezar: el juego arranca porque lo pidió él.",
    funcionoSi: "te trae el juguete, te pone la mano o empieza un movimiento mirándote para que lo sigas.",
    siNoPasa:
      "No lo sientes a jugar ni le pongas el juguete en la mano. Si hoy no arranca él, no pasa nada: mañana lo dejas a la vista otra vez.",
    duracion: "3–5 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "N4a",
    origen: { de: "mirada", refs: ["mirada:te-trae-el-otro-juguete"] },
    fuente: "Ingersoll, 2010 · Contaldo, 2016, Front Psychol",
  },
  {
    id: "el-globo-en-la-boca",
    grupo: "atencion-conjunta",
    prioridad: "alta",
    tecnica: "pausa-antes-de-lo-mejor",
    titulo: "El globo en la boca: su mirada sube a tu cara",
    tenALaMano: ["Un globo (o burbujas, o un molinillo)."],
    haz: [
      "Infla el globo y suéltalo para que vuele por el cuarto, dos veces seguidas.",
      "A la tercera, deja el globo en la boca sin soplar, mirándolo.",
      "Espera tres segundos.",
      "Cuando su mirada llegue a tu cara, o haga un gesto o un sonido, sopla.",
      "Unas pocas rondas y se acabó.",
    ],
    tuLinea: "«¿Lo inflo?…» (globo en la boca, ojos en él) «…¡Fffff!»",
    esperaVer: "Que su mirada vaya del globo a tu cara en la pausa, y vuelva al globo cuando vuela.",
    funcionoSi: "en la pausa mira del globo a tu cara, o hace un gesto o un sonido para que soples.",
    siNoPasa:
      "Sopla igual y acorta la pausa. El globo siempre a la vista: nunca lo escondas ni se lo retengas hasta que mire.",
    duracion: "3–5 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "N3",
    origen: { de: "mirada", refs: ["mirada:el-globo-en-la-boca"] },
    fuente: "Muuvila, 2022 · Halle, 1981, J Appl Behav Anal",
  },
  {
    id: "cucu-cuando-se-tapa-el",
    grupo: "atencion-conjunta",
    prioridad: "alta",
    tecnica: "pausa-antes-de-lo-mejor",
    titulo: "Cucú: cuando se tapa él",
    tenALaMano: ["Un pañuelo, o tus manos."],
    haz: [
      "Juega cucú: tápate, espera dos o tres segundos mirándolo entre los dedos, y destápate.",
      "Repítelo unas veces igual, con las mismas palabras.",
      "Deja el pañuelo a su alcance y no arranques tú.",
      "Si se tapa, tapa al muñeco o te trae el pañuelo, responde al instante con el juego completo.",
    ],
    tuLinea: "«¿Dónde está mamá?… ¡Aquí está!» · Si se tapa él: «¿Y ahora dónde estás?»",
    esperaVer:
      "Que se ría antes de que aparezcas, que intente destaparte, y un día que arranque el juego él.",
    funcionoSi: "se tapa, tapa al muñeco o te trae el pañuelo para que jueguen.",
    siNoPasa:
      "Aquí taparse es el juego, no el semáforo. Si hoy no arranca él, juega una ronda normal y déjalo ahí. No le tapes la cara a él si no le gusta, y no alargues la espera al principio.",
    duracion: "2–3 min",
    momentos: ["juego", "vestirse"],
    conQuien: "mama",
    progresion: "N4a",
    origen: { de: "mirada", refs: ["mirada:cucu-cuando-se-tapa-el"] },
    fuente: "Nomikou, 2017, Front Psychol · Halle, 1981, J Appl Behav Anal",
  },
  {
    id: "se-lo-lleva-al-hermano",
    grupo: "atencion-conjunta",
    prioridad: "alta",
    tecnica: "misma-rutina-otra-persona",
    titulo: "Se lo lleva al hermano: arranca o muestra él",
    tenALaMano: [
      "El hermano cerca, unos minutos. Además de sus reglas de siempre, para este juego: mira lo que él te muestre · di «¡uy!» y míralo a la cara · sigue su dedo cuando señale.",
      "Un juego que ya sale contigo.",
    ],
    haz: [
      "Juega con él lo que ya funciona contigo, con el hermano cerca, sin proponer nada.",
      "Si él levanta o señala algo, gira tu cuerpo hacia el hermano: «¡muéstraselo!».",
      "El hermano responde como le dijiste; tú te quedas un paso atrás, sin hablar.",
      "Si le lleva las manos o el juguete al hermano, o se le planta enfrente, el hermano arranca el juego al instante.",
      "Cierra antes de que alguno se canse y agradécele al hermano algo concreto: «seguiste su dedo».",
    ],
    tuLinea: "Al hermano: «Si te trae algo o te busca, ahí mismo le respondes, sin preguntarle nada.»",
    esperaVer:
      "Que le muestre o le señale algo al hermano como te lo hace a ti, y que lo mire esperando su reacción.",
    funcionoSi:
      "le muestra, le señala o le lleva el juego al hermano sin que tú se lo indiques, y espera su reacción.",
    siNoPasa:
      "Es normal que primero pase solo contigo. Usa el juego que más le sale y no estrenen nada con el hermano: persona nueva o juego nuevo, nunca los dos.",
    duracion: "3–5 min",
    momentos: ["juego", "transiciones"],
    conQuien: "hermano",
    progresion: "N5",
    origen: {
      de: "mirada",
      refs: ["mirada:le-lleva-el-juego-al-hermano", "anexo:D-A7", "anexo:A-A7"],
    },
    fuente: "Ferraioli, 2011 · Stokes, 1977, J Appl Behav Anal",
  },
  {
    id: "comento-no-pregunto",
    grupo: "atencion-conjunta",
    prioridad: "alta",
    tecnica: "nombro-lo-que-mira",
    titulo: "Comento, no pregunto",
    tenALaMano: ["Nada: es una forma de hablar mientras juegan."],
    haz: [
      "Durante un rato de juego, di solo lo que él está mirando o haciendo, en una o dos palabras: «corre», «arriba», «tambor».",
      "Nada de preguntas, nada de «di…», nada de «mira».",
      "Cuando haga un sonido, repite su sonido y agrega una palabra: «aaa… ¡avión!».",
      "Si señala, nombra lo que señala.",
    ],
    tuLinea: "«Corre… ¡corre el carro!»",
    esperaVer: "Más sonidos dirigidos a ti, y más miradas a tu cara mientras le hablas.",
    funcionoSi: "hace un sonido mirándote después de un comentario tuyo, o repite tu palabra.",
    siNoPasa:
      "Fíjate en tus propias preguntas, no en él: cámbialas por el nombre de lo que mira. Menos palabras tuyas, más espacio para él.",
    duracion: "3–5 min",
    momentos: ["juego", "comida", "baño"],
    conQuien: "mama",
    origen: { de: "nueva", refs: ["anexo:D-A5"] },
    fuente: "McDuffie, 2010, J Speech Lang Hear Res · Tomasello, 1986, Child Dev",
  },
  {
    id: "lo-que-hace-contigo-tiene-nombre",
    grupo: "atencion-conjunta",
    prioridad: "alta",
    tecnica: "la-respuesta-completa",
    titulo: "Lo que hace contigo tiene nombre",
    tenALaMano: ["Nada; sale mejor en las cosquillas y en la persecución."],
    haz: [
      "Cuando te mire, te sonría o venga hacia ti, nombra eso que hizo contigo: «¡me miraste!», «¡viniste!», «¡me lo mostraste!».",
      "Acompáñalo con el gesto que él ya usa: la mano de «hola».",
      "Si hay un juguete, déjalo en segundo plano: no lo nombres primero.",
      "Una vez por juego; que no se vuelva un coro.",
    ],
    tuLinea: "«¡Me miraste!»",
    esperaVer: "Que repita lo que nombraste: que te vuelva a mirar, o vuelva a venir.",
    funcionoSi: "repite dentro del mismo juego lo que nombraste: te vuelve a mirar después de «¡me miraste!».",
    siNoPasa: "Seguramente nombraste el juguete: baja el juguete y sube tu cara.",
    duracion: "2–5 min",
    momentos: ["juego"],
    conQuien: "mama",
    origen: { de: "nueva", refs: ["anexo:D-A6"] },
    fuente: "Schertz, 2022 · Schertz, 2013, Early Child Res Q",
  },
  {
    id: "en-el-piso-con-su-juguete",
    grupo: "atencion-conjunta",
    prioridad: "alta",
    tecnica: "nombro-lo-que-mira",
    titulo: "En el piso, con el juguete que él eligió",
    tenALaMano: ["El juguete que él agarre hoy. Nada que traigas tú."],
    haz: [
      "Espera a ver qué agarra él, y siéntate en el piso frente a él, cara a cara.",
      "No propongas otro juego: métete en el suyo.",
      "Nombra lo que él hace con el juguete, de a una palabra, como en «Comento, no pregunto»: «rueda», «tapa», «¡pum!».",
      "Si te aparta, retrocede un poco y sigue nombrando desde ahí.",
    ],
    tuLinea: "«¡Tapa! Suena la tapa… ¡pum!»",
    esperaVer:
      "Que te deje estar en su juego y que, de vez en cuando, levante la mirada del juguete a tu cara.",
    funcionoSi: "sigue jugando contigo al lado y te mira alguna vez mientras nombras lo que hace.",
    siNoPasa:
      "Deja lo que trajiste y vuelve a lo suyo. Menos palabras. Si el juguete lo absorbe, no compitas: haz una sola cosa pequeña con su juguete y retira las manos.",
    duracion: "5 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "N1",
    origen: {
      de: "fusion",
      refs: ["habla:interes-siéntate-en-el-piso", "habla:interes-el-juguete-que-el-eligio"],
    },
    fuente: "Carter, 2011, J Child Psychol Psychiatry · Tomasello, 1986, Child Dev",
  },

  // ════════════════ JUEGO (prioridad ahora) ════════════════
  {
    id: "el-avion-cara-a-cara",
    grupo: "juego",
    prioridad: "alta",
    tecnica: "pausa-antes-de-lo-mejor",
    titulo: "El avión, cara a cara",
    tenALaMano: ["Nada: tus brazos, y un rato en que él no tenga nada en las manos."],
    haz: [
      "Escoge un juego de cuerpo que ya le guste: el avión, levantarlo, mecerlo.",
      "Ponte de frente, a su altura, y hazlo con las mismas palabras, empezando y terminando igual.",
      "Cuando se ría o se acerque, repítelo igual.",
      "Cuando ya lo reconozca, antes de despegar detente un segundo con los brazos listos; si te mira o estira los brazos, despega.",
      "Ciérralo siempre igual: «se acabó el avión».",
    ],
    tuLinea: "«¡Avión, avión!… ¡Aterrizó!»",
    esperaVer:
      "Que se ría, se acerque o estire los brazos cuando empiezas, y que con los días espere el despegue mirándote.",
    funcionoSi:
      "se acerca o estira los brazos para que el avión vuelva a empezar, o te mira en el instante antes de despegar.",
    siNoPasa:
      "Cambia de juego, no de insistencia: prueba mecerlo o levantarlo. Hazlo solo cuando no tenga nada en las manos, y más corto.",
    duracion: "2–3 min",
    momentos: ["juego", "dormir"],
    conQuien: "mama",
    progresion: "T1",
    origen: { de: "mirada", refs: ["mirada:el-avion-cara-a-cara"] },
    fuente: "Rogers, 2012, J Am Acad Child Adolesc Psychiatry · Binns, 2022",
  },
  {
    id: "cosquillas-que-se-detienen",
    grupo: "juego",
    prioridad: "alta",
    tecnica: "pausa-antes-de-lo-mejor",
    titulo: "Cosquillas y «corre que te atrapo» que se detienen justo antes",
    tenALaMano: ["Nada: las cosquillas con su sonido de siempre, o espacio para correr."],
    haz: [
      "Haz la ronda completa dos veces igual: cosquillas con su sonido, o dos persecuciones.",
      "A la siguiente, detente justo antes de lo mejor: manos en el aire y cara de «¿y ahora?»; en la persecución, quédate de estatua cuando voltee a ver si lo sigues.",
      "Espera en silencio, tres segundos.",
      "A lo primero que haga para ti —te mira, acerca las manos, te jala, hace su sonido, dice «tú»— sigue enseguida y ponle la palabra: «¡otra vez!».",
      "De vez en cuando, en la pausa, mira hacia dos lados como si no supieras a dónde ir: si señala un lugar o una persona, el juego va para allá.",
    ],
    tuLinea: "«¡Ahí vienen las cosquillas!…» (manos quietas, cara de espera) «…¡otra vez!»",
    esperaVer:
      "Que llene la pausa con algo dirigido a ti: la mirada, las manos, su sonido, un jalón, «tú». Con el tiempo, que señale a dónde sigue el juego.",
    funcionoSi:
      "en la pausa es él quien hace seguir el juego con algo dirigido a ti, sin quedarse quieto esperando ni irse.",
    siNoPasa:
      "Acorta la pausa a un segundo, di tú «¡otra!» con el gesto y sigue. Nunca termines una pausa sin seguir el juego. Si se acelera de más, baja el ritmo.",
    duracion: "3–5 min",
    momentos: ["juego", "vestirse"],
    conQuien: "mama",
    progresion: "T1",
    origen: {
      de: "mirada",
      refs: ["mirada:cosquillas-que-se-detienen", "anexo:E-A1", "anexo:A-A6"],
    },
    fuente: "Halle, 1981, J Appl Behav Anal · Charlop, 1985, J Appl Behav Anal",
  },
  {
    id: "me-meto-en-su-juguete",
    grupo: "juego",
    prioridad: "alta",
    tecnica: "un-turno-cada-uno",
    titulo: "Me meto en su juguete",
    tenALaMano: ["El juguete que lo tiene metido. Nada que traigas tú."],
    haz: [
      "Siéntate a su altura, frente a lo que está jugando.",
      "Haz una sola acción pequeña con su juguete —empujar el carro un poquito, poner un bloque en su torre— y retira las manos.",
      "Deja que él siga.",
      "Si te aguanta, otra acción corta, y otra vez las manos atrás.",
    ],
    tuLinea: "«Me toca un poquito a mí… ¡y ahora a ti!»",
    esperaVer:
      "Al principio quizá te aparte la mano; después, que espere tu jugada y levante la mirada para ver cuándo llega.",
    funcionoSi:
      "deja tu jugada en su juego y se queda esperando la siguiente, o te mira para ver cuándo llega.",
    siNoPasa:
      "Si te aparta la mano, retírate y prueba otro día con una jugada más chiquita. No le quites el juguete ni le digas dónde ponerlo.",
    duracion: "2–3 min",
    momentos: ["juego"],
    conQuien: "mama",
    origen: { de: "mirada", refs: ["mirada:me-meto-en-su-juguete"] },
    fuente: "Carter, 2011, J Child Psychol Psychiatry · Kasari, 2006, J Child Psychol Psychiatry",
  },
  {
    id: "alto-y-ya-con-el-carro",
    grupo: "juego",
    prioridad: "alta",
    tecnica: "un-turno-cada-uno",
    titulo: "«¡Alto!… ¡ya!»: el carro se detiene en tu mano",
    tenALaMano: ["El carro, la pelota o lo que él esté rodando."],
    haz: [
      "Deja que lo empuje dos veces sin meterte.",
      "A la tercera, detén el carro con la mano y cara de travesura: «¡alto!».",
      "Espera un segundo, di «¡ya!» y suéltalo.",
      "Repítelo unas veces; cuando su mirada llegue a tu cara en el «alto», suelta de inmediato.",
      "Al final, devuélvele el carro.",
    ],
    tuLinea: "«¡Alto!…» (mano en el carro, ojos en él) «…¡ya!»",
    esperaVer:
      "Que su mirada suba del carro a tu cara en el «alto» y vuelva al carro en el «ya», un poquito más cada ronda.",
    funcionoSi:
      "en el «alto» mira del carro a tu cara, o te empuja la mano para que sueltes, y el juego sigue varias rondas.",
    siNoPasa:
      "Si se enoja, suelta enseguida y haz menos «alto». Nunca sostengas el carro más de un par de segundos.",
    duracion: "3–5 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "T2",
    origen: { de: "mirada", refs: ["mirada:alto-y-ya-con-el-carro"] },
    fuente: "Ingersoll, 2013 · Kasari, 2006, J Child Psychol Psychiatry",
  },
  {
    id: "el-me-pasa-el-turno",
    grupo: "juego",
    prioridad: "alta",
    tecnica: "un-turno-cada-uno",
    titulo: "Él me pasa el turno",
    tenALaMano: ["El juguete de los turnos de siempre."],
    haz: [
      "Jueguen los turnos de siempre un rato.",
      "Después de una ronda buena, haz tu turno y quédate sin moverte: manos abiertas sobre las piernas, cara de espera.",
      "Espera hasta cinco segundos.",
      "Si te pasa el juguete, te toma la mano o te lo acerca, responde al instante y con ganas.",
      "Si no, haz tú una ronda más y déjalo para otro día.",
    ],
    tuLinea: "«¿Me toca? ¡Dale, me toca!»",
    esperaVer:
      "Que un día te empuje el carro, te ponga el bloque en la mano o te tome la mano: te pasó el turno.",
    funcionoSi:
      "te pasa el juguete, te toma la mano o te lo acerca para que hagas tu turno, sin que se lo pidas.",
    siNoPasa:
      "No le pongas el juguete en la mano para que «te lo dé» ni le preguntes «¿me lo das?». Una espera, y si no viene, sigan jugando.",
    duracion: "3–5 min",
    momentos: ["juego"],
    conQuien: "mama",
    origen: { de: "mirada", refs: ["mirada:el-me-pasa-el-turno"] },
    fuente: "Kasari, 2010 · Whalen, 2003, J Child Psychol Psychiatry",
  },
  {
    id: "la-marcha-que-cambia",
    grupo: "juego",
    prioridad: "alta",
    tecnica: "ahora-yo-ahora-tu",
    titulo: "La marcha que cambia",
    tenALaMano: ["Nada. Espacio para marchar en fila."],
    haz: [
      "Arranca la marcha que él ya copia, unas vueltas iguales.",
      "En la siguiente, detente un segundo mirándolo y cambia una sola cosa: brazos arriba, paso de gigante o cámara lenta.",
      "Vuelve a la marcha de siempre un par de vueltas.",
      "Cambia otra cosa distinta; nunca dos cambios a la vez.",
      "Si él cambia algo por su cuenta, cópialo de inmediato y exagéralo.",
    ],
    tuLinea: "«Marcha, marcha…» (un segundo, mirándolo) «…¡de gigante!»",
    esperaVer:
      "Que te mire antes del cambio, que lo copie, y que un día proponga uno suyo y mire si lo copias. A veces, que pida seguir cuando tú ibas a parar.",
    funcionoSi:
      "la marcha sigue después de un cambio sin que se vaya y él copia el cambio; mejor aún si cambia algo él y mira si lo copias.",
    siNoPasa:
      "El cambio fue grande o rápido: hazlo mínimo (un solo brazo) y anúncialo con el sonido de siempre. Para antes de que se canse.",
    duracion: "3–5 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "T3",
    origen: { de: "nueva", refs: ["anexo:F-F1", "anexo:D-A8"] },
    fuente: "Ratner, 1978, J Child Lang · Gulsrud, 2016, J Child Psychol Psychiatry",
  },
  {
    id: "cosquillas-al-reves",
    grupo: "juego",
    prioridad: "alta",
    tecnica: "un-turno-cada-uno",
    titulo: "Cosquillas al revés, con ida y vuelta",
    tenALaMano: ["Nada al principio; después, una pluma o un peluche pequeño."],
    haz: [
      "Hazle cosquillas con el sonido del juego.",
      "Para y ofrécele tu brazo estirado —«¿a mí?»— y espera.",
      "Cuando te haga cosquillas, reacciona en grande y hazle tú enseguida: esa es la vuelta.",
      "Sigan alternando, siempre con la pausa del «¿a mí?» en medio.",
      "Cuando ya salga con las manos, dale la pluma y ofrécele el brazo.",
    ],
    tuLinea: "«¿A mí?…» (brazo estirado) «¡ay, ay, ay!… ¡ahora a ti!»",
    esperaVer:
      "Las cosquillas al revés que ya hace, ahora encadenadas; más adelante, que te haga cosquillas con la pluma en la mano.",
    funcionoSi:
      "hay ida y vuelta seguida —él a ti, tú a él, otra vez él— sin cortar el juego; o te hace cosquillas con la pluma, aunque sea un momento.",
    siNoPasa:
      "La pausa fue larga y se fue: acórtala y ofrécele el brazo más cerca. Si con la pluma no lo hace, vuelve a las manos y deja la pluma solo a la vista.",
    duracion: "2–3 min",
    momentos: ["juego", "vestirse"],
    conQuien: "mama",
    progresion: "T5",
    origen: { de: "nueva", refs: ["anexo:F-F2"] },
    fuente: "Carpenter, 2005, Infancy · Ratner, 1978, J Child Lang",
  },
  {
    id: "corre-que-te-atrapo-con-base",
    grupo: "juego",
    prioridad: "alta",
    tecnica: "pausa-antes-de-lo-mejor",
    titulo: "Corre que te atrapo, con base",
    tenALaMano: ["Un cojín o una alfombra pequeña: esa es la base."],
    haz: [
      "Persíguelo como siempre.",
      "Al atraparlo, llévalo a la base y quédate ahí: cara de espera, manos listas, sin hablar.",
      "Cuando te mire o haga un sonido, arranca otra vez.",
      "Cada tanto, en la base, cambien los papeles: tápate la cara y corre tú para que él te persiga; celebra cuando te toque.",
      "Termina en la base con «se acabó» y las manos abiertas.",
    ],
    tuLinea: "«¡Te atrapé!…» (en la base, manos listas) «…¡corre!»",
    esperaVer:
      "En la base, su señal para seguir: la mirada, un sonido, los brazos. Cuando cambian los papeles, que te persiga y te toque. Un día, que vaya él a la base para pedir otra.",
    funcionoSi:
      "el juego sigue varias rondas seguidas con parada en la base, y alguna vez es él quien persigue.",
    siNoPasa:
      "Si en la base se desconecta, acorta la parada a un segundo. Si no te persigue, muévete lento y déjate atrapar cerquita. Para antes de que se acelere de más.",
    duracion: "5–8 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "T5",
    origen: { de: "nueva", refs: ["anexo:F-F3"] },
    fuente: "Binns, 2022 · Carpenter, 2005, Infancy",
  },
  {
    id: "el-carro-va-y-viene",
    grupo: "juego",
    prioridad: "alta",
    tecnica: "un-turno-cada-uno",
    titulo: "El carro va y viene",
    tenALaMano: [
      "Un carro o una pelota que ruede bien, piso liso, y los dos sentados de frente, a un metro o dos.",
    ],
    haz: [
      "Rueda el carro hacia él con su sonido: «¡brrrum!».",
      "Espera con las manos abiertas a que lo devuelva.",
      "Cada vez que vuelva, devuélvelo igual, a su velocidad.",
      "Cuando ya vaya y venga, agrega una sola cosa: el carro choca con tu rodilla —«¡pum!»— o pasa por el túnel de tus piernas.",
      "En tu turno, señala con el dedo lo que pasa —«¡mira, se cayó!»— y míralo.",
    ],
    tuLinea: "«¡Brrrum!… ¡pum, en la rodilla!»",
    esperaVer:
      "Que el carro vuelva cada vez más; su mirada del carro a tu cara en el hueco; risa con el «¡pum!» y espera de que se repita.",
    funcionoSi:
      "el carro va y vuelve varias veces seguidas sin que tengas que recogerlo, o él lo empuja hacia ti para que hagas el «¡pum!».",
    siNoPasa:
      "Si no lo devuelve, acércate, empújalo apenas hacia ti y agradécelo en grande. Usa lo que él prefiera rodar. Si se queda con el carro, no se lo quites: rueda otro igual y espera a que te mire. Si lo nuevo rompe el juego, vuelve a lo simple.",
    duracion: "5 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "T3",
    origen: { de: "nueva", refs: ["anexo:F-F4", "anexo:A-A5"] },
    fuente: "Kasari, 2014, Pediatrics · Gulsrud, 2016, J Child Psychol Psychiatry",
  },
  {
    id: "un-paso-mas",
    grupo: "juego",
    prioridad: "alta",
    tecnica: "ahora-yo-ahora-tu",
    titulo: "Un paso más: de meter a tapar, de apilar a tumbar",
    tenALaMano: [
      "Lo que él ya use solo —un tarro para meter cosas, dos bloques para apilar— y una pieza más del mismo tipo.",
    ],
    haz: [
      "Mira qué hace él solo con el objeto y hazlo tú igual, a su lado.",
      "Cuando esté metido, agrega una vez el paso siguiente: si mete, tú tapas y sacudes; si apila, tú pones otro y lo tumbas con «¡pum!».",
      "Espera.",
      "Si repite tu paso, haz otra vez el suyo: ya es un turno.",
      "Un solo paso nuevo por rato de juego.",
    ],
    tuLinea: "«Arriba… arriba… ¡y pum!»",
    esperaVer:
      "Que meta tu paso en su juego —tumba la torre, sacude el tarro— y te mire al hacerlo; el juego dura más porque ahora tiene dos partes.",
    funcionoSi:
      "hace él las dos partes seguidas (meter y sacudir, apilar y tumbar), o te pasa la pieza para que hagas la tuya.",
    siNoPasa:
      "El paso quedó lejos de lo que él hace: baja a algo con la misma acción (otro tarro, otra pieza), no a otra acción.",
    duracion: "5 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "O2",
    origen: { de: "nueva", refs: ["anexo:F-F6"] },
    fuente: "Lifter, 1993, J Early Interv · Kasari, 2014, Pediatrics",
  },
  {
    id: "de-mentira-conmigo",
    grupo: "juego",
    prioridad: "alta",
    tecnica: "ahora-yo-ahora-tu",
    titulo: "De mentira, conmigo: la taza vacía",
    tenALaMano: ["Una taza vacía y una cuchara; más adelante, un peluche grande."],
    haz: [
      "En la merienda, haz de mentira sobre ti: bebe de la taza vacía con «glu-glu» y ríete.",
      "Ofrécele la taza y espera.",
      "Si «bebe» de mentira, hazlo tú otra vez: ya es un turno.",
      "Cuando eso salga, pásale la taza y acerca tu boca: que él te dé de beber.",
      "Solo cuando eso exista, invita al peluche.",
    ],
    tuLinea: "«Glu-glu-glu… ¡ahh!» — y le pasas la taza.",
    esperaVer: "Que «beba» de la taza vacía con el sonido; después, que te dé de beber a ti.",
    funcionoSi:
      "hace de mentira algo con la taza sobre sí mismo o sobre ti, aunque sea un momento y riéndose.",
    siNoPasa:
      "Hoy no le llamó la atención: deja la taza a la vista en las meriendas y jueguen «Un paso más». No insistas con lo de mentira.",
    duracion: "1–2 min",
    momentos: ["comida", "juego"],
    conQuien: "mama",
    progresion: "T6",
    origen: { de: "nueva", refs: ["anexo:F-F7"] },
    fuente: "Lifter, 2011, Infants Young Child · Kasari, 2014, Pediatrics",
  },
  {
    id: "lucha-suave-con-senal",
    grupo: "juego",
    prioridad: "alta",
    tecnica: "pausa-antes-de-lo-mejor",
    titulo: "Lucha suave con señal de «¡ya!» y de «¡alto!»",
    tenALaMano: ["Dos almohadas o una manta, y piso blando."],
    haz: [
      "Muéstrale las dos señales: brazos arriba y «¡ya!» para empezar; manos abiertas y «¡alto!» para parar.",
      "Haz la señal de «¡ya!», empújalo suave con la almohada y deja que te tumbe; cae exagerando, en cámara lenta.",
      "Al rato, haz la señal de «¡alto!» y quédate sin moverte, mirándolo.",
      "Espera su señal para seguir —la mirada, los brazos, un sonido o su «¡ya!»— y arranca otra vez; si no llega, arranca igual.",
      "Cambien los papeles: ahora lo tumbas tú, suave; luego él a ti. Unas rondas y se cierra.",
    ],
    tuLinea: "«¡Ya!» (brazos arriba) … «¡Alto!» (manos abiertas, sin moverte)",
    esperaVer:
      "Que pare en el «alto», o casi; que pida seguir con algo; y un día, que haga él la señal de empezar.",
    funcionoSi:
      "el juego para y vuelve a arrancar varias veces, y alguna vez él da la señal de empezar antes que tú.",
    siNoPasa:
      "Si no para, las rondas fueron largas: hazlas más cortas. Si se acelera de más, cambia a mecerlo despacio y termina. Nunca antes de dormir.",
    duracion: "3–5 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "T2",
    origen: { de: "nueva", refs: ["anexo:F-F10"] },
    fuente: "StGeorge, 2017, Infant Ment Health J · Binns, 2022",
  },
  {
    id: "con-el-hermano-la-misma-rutina",
    grupo: "juego",
    prioridad: "alta",
    tecnica: "misma-rutina-otra-persona",
    titulo: "Con el hermano: la misma rutina, con las mismas palabras",
    tenALaMano: [
      "El hermano, cinco minutos, y sus reglas de siempre, dichas antes: haz una sola cosa · espera cinco segundos · cópialo a él.",
      "El juego que mejor le sale contigo: la marcha, las cosquillas, «¡alto!… ¡ya!» o los dos juguetes iguales.",
    ],
    haz: [
      "Juega tú una ronda, con el hermano al lado mirando.",
      "Luego alternen: una ronda tú, una ronda el hermano, calcada, con tus mismas palabras y tu misma pausa.",
      "Cuando salga, el hermano juega solo con él; tú te quedas detrás del hermano, sin hablar.",
      "Si el hermano manda, corrige o apura, tócale el hombro: «espera».",
      "Cierra corto y agradécele al hermano algo concreto: «esperaste, y te miró».",
    ],
    tuLinea: "Al hermano: «Igualito que yo: haz una cosa, espera, y copia lo que él haga.»",
    esperaVer:
      "Que mire al hermano como te mira a ti en el juego, que siga su marcha o corra para que lo persiga, que haga pruebas para ver si lo copia, y que le haga cosquillas también a él.",
    funcionoSi:
      "hace con el hermano algo que ya hacía contigo —adelantarse, copiar, pedir que siga— sin que tú dirijas el juego.",
    siNoPasa:
      "El hermano fue rápido o hizo de maestro: vuelvan a un solo juego que ya le sale, más corto. Persona nueva o juego nuevo, nunca los dos el mismo día.",
    duracion: "3–5 min",
    momentos: ["juego"],
    conQuien: "hermano",
    progresion: "T7",
    origen: {
      de: "fusion",
      refs: [
        "mirada:el-hermano-lo-copia",
        "mirada:los-mismos-turnos-con-el-hermano",
        "mirada:el-hermano-al-lado-un-turno-cada-uno",
        "mirada:las-mismas-cosquillas-con-el-hermano",
        "anexo:B-A9",
        "anexo:F-F9",
      ],
    },
    fuente: "Walton, 2012 · Bene, 2020 · Stokes, 1977, J Appl Behav Anal",
  },

  // ════════════════ SEÑALAR ════════════════
  {
    id: "mama-senala-el-mundo",
    grupo: "senalar",
    prioridad: "normal",
    tecnica: "algo-que-mostrar",
    titulo: "Mamá señala el mundo",
    tenALaMano: ["Nada: lo que haya en la casa o en la ruta de la marcha."],
    haz: [
      "Mientras marchan o caminan, para en seco y señala con el dedo algo que se mueva o suene.",
      "Di su nombre con voz de sorpresa: «¡mira! ¡el avión!».",
      "Mira la cosa, luego su cara, luego la cosa otra vez.",
      "Espera unos segundos a que él mire lo que señalas.",
      "Cuando mire, celébralo en dos palabras y sigan marchando. Cada vez, algo distinto.",
    ],
    tuLinea: "«¡Mira!… ¡el avión!»",
    esperaVer:
      "Que mire lo que señalas y vuelva a tu cara; con los días, que se adelante a buscar qué vas a señalar.",
    funcionoSi:
      "frena cuando tú frenas, mira lo que señalas y te mira a ti antes de seguir; o saca el dedo hacia algo por su cuenta y te mira.",
    siNoPasa:
      "Baja a su altura para que tu dedo le quede a la vista, y señala algo más cerca que se mueva o suene.",
    duracion: "1–2 min",
    momentos: ["juego", "calle", "transiciones"],
    conQuien: "mama",
    progresion: "S1",
    origen: { de: "nueva", refs: ["anexo:A-A1"] },
    fuente: "Matthews, 2012, Dev Sci · Rowe, 2009, Science",
  },
  {
    id: "la-respuesta-completa",
    grupo: "senalar",
    prioridad: "normal",
    tecnica: "la-respuesta-completa",
    titulo: "La respuesta completa: cada vez que señala o dice «tú»",
    tenALaMano: ["Nada: es una forma de responder, todo el día."],
    haz: [
      "Cuando señale, te muestre algo o diga «tú» señalando, deja lo que estás haciendo.",
      "Mira lo que señala, luego su cara con emoción —«¡uy, sí!»—, y otra vez la cosa.",
      "Nómbralo en una o dos palabras y agrega su sonido o lo que hace: «¡el carro! brrum».",
      "Si pide algo con el dedo, nómbralo y dáselo enseguida, sin pedirle que lo repita.",
      "Si vuelve a señalar, dale la respuesta entera otra vez, sin acortarla.",
    ],
    tuLinea: "«¡Tú! Sí… ¡te toca a ti!» · «¡Uy, el carro!»",
    esperaVer:
      "Que sostenga el gesto más tiempo, que lo repita mirándote a la cara, y que aparezcan sonidos pegados al dedo.",
    funcionoSi:
      "después de señalar busca tu cara y espera, o señala enseguida otra cosa para volver a recibir la respuesta.",
    siNoPasa:
      "Revisa qué mitad faltó: ¿miraste solo la cosa? ¿le sonreíste solo a él? Hacen falta las dos. Y nada de «¿qué es eso?»: la frase corta, sin pregunta.",
    duracion: "1 min",
    momentos: ["juego", "comida", "calle", "baño"],
    conQuien: "mama",
    progresion: "S4",
    origen: {
      de: "nueva",
      refs: ["anexo:A-A2", "anexo:C-C4", "anexo:D-A1", "habla:sonidos-senalar-ya-es-hablar"],
    },
    fuente: "Liszkowski, 2004, Dev Sci · Dimitrova, 2016",
  },
  {
    id: "mira-lo-que-traigo",
    grupo: "senalar",
    prioridad: "normal",
    tecnica: "algo-que-mostrar",
    titulo: "Mira lo que traigo: mostrar y dar",
    tenALaMano: [
      "Tres o cuatro cosas pequeñas que le gusten (algo que suene, algo que gire, la pluma de las cosquillas), en tu bolsillo o en una bolsa.",
    ],
    haz: [
      "Al terminar una ronda de persecución o de marcha, saca una y levántala a la altura de tu cara: «¡mira!».",
      "Espera a que la mire, y dásela.",
      "Cuando la tenga, extiende la mano abierta y espera: si te la da, devuélvesela enseguida.",
      "Si te la muestra o la señala por su cuenta, nómbrala y celébralo como un tesoro; no pidas nada más.",
      "Si el hermano está cerca, gira tu cuerpo hacia él —«¡muéstrasela!»— y que él responda: mira la cosa, mira su cara y la nombra.",
    ],
    tuLinea: "«¡Mira!…» (a la altura de tu cara) «…¡la pluma!»",
    esperaVer:
      "Que mire la cosa y tu cara, que te la dé y la reciba; un día, que te la muestre o la levante hacia alguien sin que se lo pidan.",
    funcionoSi:
      "te levanta o te extiende algo hacia la cara mirándote, sin que le hayas extendido la mano, aunque no lo suelte.",
    siNoPasa:
      "Empieza por dar, que es más fácil que mostrar, con su cosa favorita. Toma como muestra cualquier brazo extendido. Nunca se lo quites de la mano.",
    duracion: "1–3 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "S3",
    origen: {
      de: "nueva",
      refs: ["anexo:A-A3", "anexo:D-A4", "anexo:F-F8", "anexo:E-A7"],
    },
    fuente: "Cameron-Faulkner, 2015, Infancy · Kasari, 2006, J Child Psychol Psychiatry",
  },
  {
    id: "la-sorpresa-en-la-ruta",
    grupo: "senalar",
    prioridad: "normal",
    tecnica: "algo-que-mostrar",
    titulo: "La sorpresa en la ruta",
    tenALaMano: [
      "Algo que aparezca de golpe: un globo, una linterna, un muñeco bajo un trapo; o un zapato para ponerte en la cabeza.",
    ],
    haz: [
      "En medio de la marcha o de la persecución, deja que la sorpresa aparezca donde él la vea y tú no: mira hacia otro lado.",
      "Quédate sin moverte unos segundos: es su oportunidad de mostrártela.",
      "Si la señala, hace un sonido o te jala, dale la respuesta completa, con sorpresa grande.",
      "Si no, «descúbrela» tú: señálala, nómbrala y míralo.",
      "Otro día, la variante: marcha con el zapato en la cabeza, sin decir nada y seria, y espera.",
    ],
    tuLinea: "«¡Uy!… ¡un globo!» · «¿El zapato… en la cabeza?»",
    esperaVer:
      "Que mire la sorpresa, te mire a ti y haga algo para que tú la veas; con el zapato, risa dirigida a ti.",
    funcionoSi:
      "te mira a ti y a la sorpresa antes de que tú hagas nada, o la señala sin querer que se la den.",
    siNoPasa:
      "Una sorpresa más grande, que se mueva y suene, y menos espera. Si la pide con la mano, dásela y, si el hermano está cerca, muéstrensela juntos. Nunca la misma dos veces seguidas.",
    duracion: "1 min",
    momentos: ["juego", "calle"],
    conQuien: "mama",
    progresion: "S4",
    origen: { de: "nueva", refs: ["anexo:A-A4", "anexo:D-A2", "anexo:D-A9"] },
    fuente: "Gulsrud, 2007 · Liszkowski, 2004, Dev Sci",
  },

  // ════════════════ INTENCIÓN COMUNICATIVA ════════════════
  {
    id: "burbujas-y-espero",
    grupo: "intencion-comunicativa",
    prioridad: "normal",
    tecnica: "espero-en-silencio",
    titulo: "Burbujas: soplo, cierro el frasco y espero",
    tenALaMano: ["Un frasco de burbujas."],
    haz: [
      "Sopla dos rondas seguidas para que se enganche.",
      "Cierra la varita en el frasco y sostenlo a la altura de tu cara.",
      "Espera en silencio, mirándolo, unos segundos.",
      "Cuando te mire, señale, estire la mano o haga un sonido, sopla al instante: «¡más burbujas!».",
      "Si no pasa nada, sopla igual.",
    ],
    tuLinea: "(nada: cara de espera, frasco a la vista)… «¡Más burbujas!»",
    esperaVer: "Que llene el silencio con algo: la mirada, un gesto, un sonido, la mano estirada.",
    funcionoSi: "en el silencio te pide que soples con la mirada, un gesto o un sonido dirigido a ti.",
    siNoPasa:
      "No preguntes «¿quieres más?» ni «¿qué dices?». Acorta la espera y sopla igual: el silencio vuelve a funcionar otro día.",
    duracion: "3–5 min",
    momentos: ["juego", "baño"],
    conQuien: "mama",
    origen: { de: "mirada", refs: ["mirada:burbujas-y-espero"] },
    fuente: "Halle, 1981, J Appl Behav Anal · Muuvila, 2022",
  },
  {
    id: "lo-dejo-a-medias",
    grupo: "intencion-comunicativa",
    prioridad: "normal",
    tecnica: "espero-en-silencio",
    titulo: "Lo dejo a medias para que él lo traiga",
    tenALaMano: [
      "El juego que acaba de gustarle, a la vista y a su alcance: el frasco cerrado, el globo desinflado, el carro en su sitio.",
    ],
    haz: [
      "Al terminar un juego que le gustó, deja las cosas a la vista y a su alcance.",
      "Sigue con lo tuyo cerca de él, sin mirarlo fijamente.",
      "Si trae el objeto, te toma la mano o te llama desde el juego, responde con el juego entero y con ganas.",
      "Si hoy no pasa, mañana lo dejas otra vez.",
    ],
    tuLinea: "«¡Ah, quieres burbujas! Dale, aquí vamos.»",
    esperaVer: "Que un día te traiga el objeto, te lo ponga en la mano o te lleve hasta el juego.",
    funcionoSi: "te trae el objeto, te lleva de la mano o te llama para que el juego vuelva a empezar.",
    siNoPasa:
      "No le preguntes «¿quieres jugar?» ni le acerques tú el objeto. Y no lo dejes a medias cuando está cansado o con hambre.",
    duracion: "5 min",
    momentos: ["juego", "transiciones"],
    conQuien: "mama",
    origen: { de: "mirada", refs: ["mirada:lo-dejo-a-medias"] },
    fuente: "Charlop, 1985, J Appl Behav Anal · Ingersoll, 2013",
  },
  {
    id: "una-media-puesta",
    grupo: "intencion-comunicativa",
    prioridad: "normal",
    tecnica: "espero-en-silencio",
    titulo: "Una media puesta, la otra en la mano",
    tenALaMano: [
      "Nada: una rutina del día que ya se sepa (vestirse, la comida, la toalla) o un juego de memoria («uno, dos… ¡y!»).",
    ],
    haz: [
      "Haz la primera parte de la rutina normal.",
      "Antes de la segunda, detente con lo que sigue a la vista: la otra media en tu mano, la cuchara a medio camino, la toalla lista.",
      "Espera en silencio, con cara de «¿y ahora?», unos segundos.",
      "Si te mira, hace un gesto o un sonido, sigue de inmediato y nómbralo: «¡la otra!».",
      "Si no, sigue igual. Una o dos veces al día, nunca con prisa.",
    ],
    tuLinea: "«Una media…» (la otra en la mano, silencio) «…¡y la otra!»",
    esperaVer:
      "Que llene el hueco con la mirada, un gesto o un sonido, en momentos del día que nadie preparó.",
    funcionoSi:
      "en la pausa de una rutina de todos los días te pide que sigas, con la mirada, un gesto o un sonido.",
    siNoPasa:
      "Si la rutina está tensa o van tarde, ese día no hay pausa. La ropa o la comida nunca se retienen como premio.",
    duracion: "1–2 min",
    momentos: ["vestirse", "comida", "baño"],
    conQuien: "mama",
    origen: {
      de: "mirada",
      refs: ["mirada:una-media-puesta", "habla:espera-el-hueco-de-la-rutina"],
    },
    fuente: "Halle, 1981, J Appl Behav Anal · Stokes, 1977, J Appl Behav Anal",
  },
  {
    id: "de-a-poquitos",
    grupo: "intencion-comunicativa",
    prioridad: "normal",
    tecnica: "espero-en-silencio",
    titulo: "De a poquitos: cada pedacito es un turno",
    tenALaMano: [
      "Algo que quiera y se pueda dar en partes: una galleta partida, uvas, bloques de a uno, un sorbo en el vaso.",
    ],
    haz: [
      "Dale una parte pequeña.",
      "Espera, mirándolo, a que pida la siguiente: te mira, estira la mano, hace un sonido o dice «más»; si no pide, dásela igual.",
      "Dale la siguiente y nómbrala: «¡más! ¡más galleta!».",
      "Sigan así unas vueltas; cada vez espera un instante más.",
      "A la última: «¡se acabó!», con las manos abiertas, y «chao».",
    ],
    tuLinea: "«¿Más?… ¡más!»",
    esperaVer: "Una cadena: pide, recibe, pide, recibe, con la mirada en cada vuelta.",
    funcionoSi:
      "pide cada pedacito varias veces seguidas, cada vez con algo dirigido a ti, sin frustrarse.",
    siNoPasa:
      "Pedazos más grandes y menos vueltas. Si se frustra, dale el resto y cierra con calma. Nunca lo hagas esperar por castigo.",
    duracion: "3–5 min",
    momentos: ["comida", "juego"],
    conQuien: "mama",
    origen: { de: "habla", refs: ["habla:espera-de-a-poquitos", "anexo:E-A8"] },
    fuente: "Ostrosky, 1991 · Halle, 1981, J Appl Behav Anal",
  },
  {
    id: "espera-con-cara-de-pregunta",
    grupo: "intencion-comunicativa",
    prioridad: "normal",
    tecnica: "espero-en-silencio",
    titulo: "Espera con cara de pregunta",
    tenALaMano: ["Nada: lo que él quiera en ese momento (el jugo, la puerta, el juguete)."],
    haz: [
      "Sostén lo que quiere a la vista, míralo con las cejas arriba y cierra la boca.",
      "Cuenta hasta cinco por dentro, sin adivinar lo que quiere.",
      "Lo que salga —un sonido, un gesto, un jalón—, respóndelo nombrando y dáselo: «¿jugo? ¡jugo!».",
      "Si no sale nada, dáselo igual y nómbralo.",
      "Si le pides algo, dilo una sola vez y espera.",
    ],
    tuLinea: "(cejas arriba, boca cerrada, contando por dentro)… «¿Jugo? ¡Jugo!»",
    esperaVer: "Que en tu silencio aparezca algo suyo: un sonido, un gesto, un jalón, una mirada a tu cara.",
    funcionoSi: "en tu silencio pide él, a su manera, antes de que tú hables o adivines.",
    siNoPasa:
      "Nunca lo dejes sin la cosa por no pedir: se la das igual. Si te descubres repitiendo «dame, dame, dame», vuelve a decirlo una sola vez. Si le pides algo y no responde, muéstraselo con tu cuerpo; y si tampoco, háganlo juntos.",
    duracion: "1 min",
    momentos: ["comida", "juego", "transiciones"],
    conQuien: "mama",
    origen: {
      de: "fusion",
      refs: [
        "habla:sonidos-espera-con-cara-de-pregunta",
        "habla:espera-cuenta-cinco",
        "habla:espera-no-adivines",
        "habla:espera-tres-segundos-mas",
        "anexo:C-C7",
      ],
    },
    fuente: "Kaiser, 2013, J Speech Lang Hear Res · Halle, 1981, J Appl Behav Anal",
  },
  {
    id: "el-frasco-que-no-abre",
    grupo: "intencion-comunicativa",
    prioridad: "normal",
    tecnica: "espero-en-silencio",
    titulo: "El frasco que no abre",
    tenALaMano: [
      "Lo que le gusta, en un frasco transparente con tapa apretada o en su bolsa cerrada: burbujas, una galleta, su carro en una caja con tapa.",
    ],
    haz: [
      "Sopla burbujas o cómanse un pedacito, dos veces.",
      "Cierra bien el frasco y pónselo en la mano.",
      "Espera cerca, en silencio, con cara de «¿y ahora?».",
      "Cuando te lo devuelva, te mire, lo empuje hacia ti o haga un sonido, di «¡abre!» y ábrelo ya.",
      "Cuando ya le salga, estira un poquito la espera, un día a la vez. Cierra con «chao, burbujas».",
    ],
    tuLinea: "«Uy, no abre…» (silencio, cara de espera) «…¡abre! ¡Abre!»",
    esperaVer: "Que te entregue el frasco mirándote, o lo empuje hacia ti con un sonido.",
    funcionoSi:
      "te pide ayuda juntando el frasco hacia ti con la mirada, o un gesto con un sonido.",
    siNoPasa:
      "Muéstrale tú «abre» con el gesto de girar, y ábrelo. Si lo deja y se va, no lo persigas con el frasco. Si lo ves frustrado, la espera fue larga: vuelve a una corta.",
    duracion: "2–3 min",
    momentos: ["comida", "juego"],
    conQuien: "mama",
    origen: {
      de: "fusion",
      refs: [
        "mirada:la-espera-se-estira",
        "habla:espera-el-frasco-dificil",
        "habla:focalizada-palabra-abre",
        "anexo:E-A3",
      ],
    },
    fuente: "Charlop, 1985, J Appl Behav Anal · Wetherby, 1989, Semin Speech Lang",
  },
  {
    id: "marchar-con-tropiezo",
    grupo: "intencion-comunicativa",
    prioridad: "normal",
    tecnica: "pausa-antes-de-lo-mejor",
    titulo: "Marchar con tropiezo",
    tenALaMano: ["Dos cucharas de palo y dos ollas: un tambor para cada uno."],
    haz: [
      "Marchen como siempre, con el tambor: golpea y di «pum» a cada paso.",
      "Cuando esté copiando, equivócate: para de golpe, marcha hacia atrás o golpea sin sonido.",
      "Espera unos segundos, mirándolo; si no reacciona, vuelve a marchar igual.",
      "A cualquier protesta o pedido —te mira, te jala, hace «pum», dice «no»—: «¡ah, pum! ¡vamos!», y siguen.",
      "Cierra con «chao, tambor» y la mano de chao.",
    ],
    tuLinea: "«Pum, pum, pum…» (paras en seco) «…¡ah, pum! ¡vamos!»",
    esperaVer: "Que proteste o pida que sigas, dirigido a ti, y que copie el golpe con su «pum».",
    funcionoSi:
      "reacciona a tu «error» dirigiéndose a ti —mirada y gesto, o un sonido— y vuelve a marchar contigo.",
    siNoPasa:
      "Menos errores: uno por ronda, y más marcha normal. Si el tambor lo absorbe, hazlo sin nada en las manos.",
    duracion: "2–3 min",
    momentos: ["juego"],
    conQuien: "mama",
    origen: { de: "nueva", refs: ["anexo:E-A2"] },
    fuente: "Carter, 2001 · Ingersoll, 2010, J Speech Lang Hear Res",
  },
  {
    id: "dos-cosas-una-eleccion",
    grupo: "intencion-comunicativa",
    prioridad: "normal",
    tecnica: "le-doy-a-elegir",
    titulo: "Dos cosas, una elección",
    tenALaMano: [
      "Dos opciones que de verdad quiera, bien visibles: dos frutas, dos juguetes, o «¿cosquillas o correr?» con las manos que lo muestran.",
    ],
    haz: [
      "Sostén las dos a su altura, separadas.",
      "Nómbralas una vez: «¿uva… o pan?».",
      "Espera.",
      "Cuando señale, mire o toque una, dásela enseguida y nómbrala: «¡uva!».",
      "Si agarra las dos, ofrécelas otra vez con las manos más separadas.",
    ],
    tuLinea: "«¿Uva… o pan?» — y esperas.",
    esperaVer: "Que señale o toque una mirándote; a veces, la palabra o un pedacito de ella.",
    funcionoSi: "elige con algo dirigido a ti (el dedo y la mirada, o la palabra) y acepta lo que eligió.",
    siNoPasa: "Elige tú por él diciendo lo que ves —«¡miras la uva!»— y dásela. Mañana otra vez.",
    duracion: "1 min",
    momentos: ["comida", "juego"],
    conQuien: "mama",
    origen: { de: "nueva", refs: ["anexo:E-A4", "habla:frases-elige-tu-o-yo"] },
    fuente: "Ostrosky, 1991 · Wetherby, 1989, Semin Speech Lang",
  },
  {
    id: "chao-a-tres-silencio-al-cuarto",
    grupo: "intencion-comunicativa",
    prioridad: "normal",
    tecnica: "espero-en-silencio",
    titulo: "«Chao» a tres, silencio al cuarto",
    tenALaMano: ["Tres o cuatro juguetes para guardar, los patos al final del baño, o el peluche."],
    haz: [
      "Al guardar cada juguete, di «chao» con la mano y la voz, exagerado.",
      "Repítelo con el segundo y el tercero.",
      "Con el cuarto, guárdalo en silencio y espera, mirándolo.",
      "Si hace «chao» —con la mano, con la voz o con las dos—, celébralo y ponle tú el gesto y la palabra encima.",
      "Al revés, con «hola»: el peluche sale de debajo de la mesa saludando tres veces; la cuarta, sale callado.",
    ],
    tuLinea: "«¡Chao, carro!… ¡chao, pelota!… ¡chao, tambor!…» (el cuarto, en silencio)",
    esperaVer:
      "Que haga «chao» u «hola» sin que tú lo hayas hecho justo antes: al juguete, o al hermano.",
    funcionoSi: "saluda o se despide sin que tú lo hayas hecho justo antes: lo empieza él, no lo copia.",
    siNoPasa: "Haz un par de vueltas más con el «chao» completo y prueba otro día. Nunca «¿cómo se dice?».",
    duracion: "1–2 min",
    momentos: ["transiciones", "baño", "juego"],
    conQuien: "mama",
    origen: { de: "nueva", refs: ["anexo:E-A5"] },
    fuente: "Charlop, 1985, J Appl Behav Anal · Wetherby, 1989, Semin Speech Lang",
  },
  {
    id: "lo-que-no-le-gusta",
    grupo: "intencion-comunicativa",
    prioridad: "normal",
    tecnica: "le-doy-a-elegir",
    titulo: "Lo que no le gusta: su «no» se escucha",
    tenALaMano: ["Una comida o un objeto que claramente no quiere."],
    haz: [
      "Ofrécelo con naturalidad, cerca, sin insistir.",
      "Espera.",
      "A cualquier «no» —empuja, aparta la cara, niega con la cabeza, un sonido, «no»—, retíralo de inmediato y ponle la palabra: «¡no quieres! Listo».",
      "Enseguida ofrécele algo que sí le gusta, y dáselo cuando lo pida.",
      "Una sola vez por comida, y no todos los días.",
    ],
    tuLinea: "«¡No quieres! Listo.» — y lo retiras.",
    esperaVer: "Un «no» claro dirigido a ti, sin llegar al llanto.",
    funcionoSi:
      "rechaza con algo que tú entiendes —gesto y mirada, o la palabra— y la cosa se va antes de que se enoje.",
    siNoPasa:
      "Si se enoja sin avisar, lo ofreciste muy cerca o por mucho rato: la próxima vez, más lejos y más corto.",
    duracion: "1 min",
    momentos: ["comida"],
    conQuien: "mama",
    origen: { de: "nueva", refs: ["anexo:E-A6"] },
    fuente: "Wetherby, 1989, Semin Speech Lang · Trembath, 2022",
  },

  // ════════════════ COMPRENDER ════════════════
  {
    id: "lo-que-el-mira-yo-lo-nombro",
    grupo: "comprender",
    prioridad: "normal",
    tecnica: "nombro-lo-que-mira",
    titulo: "Lo que él mira, yo lo nombro, donde estemos",
    tenALaMano: [
      "Nada: lo que él tenga en la mano o esté mirando, en la casa, en el carro, en el mercado, en el parque o en la calle.",
    ],
    haz: [
      "Mira lo que él mira o sostiene, y ponte a su altura.",
      "Nómbralo en una frase corta: «¡el carro!», «el carro corre».",
      "Espera en silencio unos segundos.",
      "Si sigue con lo mismo, repite la frase una vez con lo que él hace; no traigas nada nuevo.",
      "Fuera de la casa, igual: en el carro, «¡moto!»; en el mercado, lo que él mire del estante; en el parque, «¡sube!… ¡baja!» con el columpio.",
    ],
    tuLinea: "«¡El carro!… el carro corre.»",
    esperaVer:
      "Que siga en lo suyo, a veces te mire y vuelva a la cosa, y a veces repita la vocal o la última sílaba.",
    funcionoSi:
      "otro día, en otro lugar, al oír la palabra sola —sin gesto, y tú mirándolo a él— busca la cosa, se voltea hacia ella o la trae.",
    siNoPasa:
      "El momento no estaba limpio (muchas cosas, prisa, mucha agitación): nombra solo cuando una sola cosa le llene la vista. Nada de preguntas ni de «di…».",
    duracion: "1 min",
    momentos: ["juego", "comida", "calle", "baño"],
    conQuien: "mama",
    progresion: "P2",
    origen: {
      de: "fusion",
      refs: [
        "habla:modelado-nombra-su-mundo",
        "habla:interes-el-manda",
        "habla:focalizada-el-nombre-vive-en-la-cosa",
        "habla:modelado-en-el-carro",
        "habla:modelado-mercado",
        "habla:modelado-parque",
        "habla:modelado-la-calle",
        "habla:interes-nombra-lo-que-el-hace",
        "anexo:C-C1",
      ],
    },
    fuente: "Tomasello, 1986, Child Dev · McGillion, 2017, J Child Psychol Psychiatry",
  },
  {
    id: "las-mismas-palabras",
    grupo: "comprender",
    prioridad: "normal",
    tecnica: "nombro-lo-que-mira",
    titulo: "Las mismas palabras, en los mismos momentos",
    tenALaMano: [
      "Una rutina fija (el baño, vestirse, la mesa, la noche) y tres o cuatro frases cortas que vas a decir idénticas cada vez: «brazo arriba», «zapato… ¡pie!», «agua caliente», «a la cama».",
    ],
    haz: [
      "Escoge una sola rutina y sus frases.",
      "Di cada frase justo antes del paso, con el objeto a la vista.",
      "Repite las mismas frases cada día, con la misma voz.",
      "Cuando ya las conozca, di la frase antes de mover las manos, y espera un momento.",
      "Al terminar cada paso, el «chao» que ya hace: «chao, agua».",
    ],
    tuLinea: "«Brazo arriba…» (la camiseta todavía en la silla, y esperas)",
    esperaVer:
      "Al principio hace el paso porque la rutina lo anuncia; después, empieza a adelantarse a tu frase.",
    funcionoSi:
      "hace el paso al oír la frase, antes de que muevas las manos o muestres el objeto.",
    siNoPasa:
      "Las frases cambiaron de un día a otro o son largas: recórtalas a dos o tres palabras, siempre bien dichas. Una rutina a la vez.",
    duracion: "1–2 min",
    momentos: ["baño", "vestirse", "comida", "dormir"],
    conQuien: "mama",
    progresion: "P2",
    origen: {
      de: "fusion",
      refs: [
        "habla:modelado-mismas-palabras-rutina",
        "habla:modelado-hora-de-dormir",
        "anexo:C-C2",
      ],
    },
    fuente: "Fernald, 2006, Dev Sci · Childers, 2002, Dev Psychol",
  },
  {
    id: "su-palabra-mas-una",
    grupo: "comprender",
    prioridad: "normal",
    tecnica: "su-palabra-mas-una",
    titulo: "Su palabra, más una, sin corregir",
    tenALaMano: ["Nada: sus palabras sueltas, sus vocales, su «tú», su «chao»."],
    haz: [
      "Cuando diga algo, devuélveselo bien dicho y con una palabra más: «tú» → «¡tú corres!»; «agu» → «¡agua! agua fría».",
      "No corrijas: nada de «no», «así no», «repite» ni «se dice…».",
      "Háblale a su tamaño: frases de dos a cuatro palabras, bien armadas.",
      "Una frase tuya, un turno de él: deja el espacio.",
    ],
    tuLinea: "Él: «agu». Tú: «¡Agua! Agua fría.» — y se la das.",
    esperaVer: "Que sostenga el turno, te mire y a veces repita la última palabra.",
    funcionoSi:
      "en la rutina de siempre, con dos cosas a la vista y tú sin mirar ninguna, te da la que dice tu frase; o repite tu palabra de más.",
    siNoPasa:
      "Estás hablando de más o muy cortado: vuelve a una frase tuya por un turno suyo, con frases cortas y completas. Nunca le pidas que lo diga.",
    duracion: "3–5 min",
    momentos: ["juego", "comida", "baño", "vestirse"],
    conQuien: "mama",
    progresion: "P2",
    origen: {
      de: "fusion",
      refs: [
        "habla:modelado-habla-a-su-tamano",
        "habla:recast-devuelve-la-palabra",
        "habla:recast-su-palabra-mas-una",
        "habla:recast-repite-bien-sin-corregir",
        "habla:frases-una-palabra-mas-una",
        "habla:frases-recast-sin-corregir",
        "anexo:C-C6",
      ],
    },
    fuente: "Cleave, 2015, Am J Speech Lang Pathol · Roberts, 2011, Am J Speech Lang Pathol",
  },
  {
    id: "una-palabra-muchas-veces",
    grupo: "comprender",
    prioridad: "normal",
    tecnica: "nombro-lo-que-mira",
    titulo: "Una palabra o un sonido, muchas veces, en muchos lugares",
    tenALaMano: [
      "Una palabra útil para él («más», «abre», «ya», «agua») o un sonido («aaah», «brum») para esta semana.",
    ],
    haz: [
      "Escoge la palabra o el sonido de la semana.",
      "Dilo cada vez que pase: en el juego, en la comida, en el baño, al despedirte, en la calle.",
      "Si es una palabra de hacer («dame», «para», «ven»), dila primero con su gesto: la mano abierta, la palma, los brazos abiertos.",
      "Cuando responda al gesto casi siempre, di la palabra primero, espera un momento, y solo entonces agrega el gesto.",
      "No le pidas que la repita, ni una vez.",
    ],
    tuLinea: "«¡Agua!» en la ducha, en el vaso, en la lluvia: la misma palabra.",
    esperaVer: "Que al principio responda al gesto, y poco a poco, antes de que llegue el gesto.",
    funcionoSi:
      "en un juego de verdad responde a la palabra dicha sin gesto —se para con «¡para!», viene con «¡ven!»— mientras tú sigues sin moverte.",
    siNoPasa:
      "Usa solo palabras que hagan seguir algo que le importa: la persecución, las cosquillas, la marcha. Nunca la misma consigna varias veces seguidas.",
    duracion: "1 min",
    momentos: ["juego", "comida", "baño", "calle"],
    conQuien: "mama",
    progresion: "P2",
    origen: {
      de: "fusion",
      refs: [
        "habla:focalizada-palabra-semana",
        "habla:sonidos-un-solo-sonido-todo-el-dia",
        "habla:focalizada-misma-palabra-cinco-lugares",
        "anexo:C-C3",
      ],
    },
    fuente: "Childers, 2002, Dev Psychol · McNeil, 2000",
  },
  {
    id: "la-cancion-de-siempre-al-vestirlo",
    grupo: "comprender",
    prioridad: "normal",
    tecnica: "canto-a-su-ritmo",
    titulo: "La canción de siempre, al vestirlo y en el baño",
    tenALaMano: [
      "La canción que mejor le funciona jugando, o una cancioncita de tres palabras para un momento: «a guardar, a guardar».",
    ],
    haz: [
      "Cántala tal cual en un momento distinto: mientras lo vistes, en la tina, caminando a la tienda.",
      "Deja su hueco de siempre antes de lo mejor, y espera.",
      "Al vestirlo, levanta cada prenda, espera a que la mire y nómbrala: «¡media!».",
      "Si te mira o hace la señal, sigues; si no, sigues igual.",
      "Un momento nuevo por semana, no todos a la vez.",
    ],
    tuLinea: "(al ponerle la camiseta) «Las ruedas del bus van…» (pausa) «…¡ruedan y ruedan!»",
    esperaVer:
      "Que la canción le anuncie el momento: se acomoda, te mira en el hueco, a veces levanta el brazo antes de que se lo pidas.",
    funcionoSi:
      "en un momento que no se preparó te mira en el hueco de la canción, o hace el gesto que la canción anuncia.",
    siNoPasa:
      "No estrenes canción y momento a la vez. Si en ese momento está incómodo (el agua, la ropa), ese día no hay canción.",
    duracion: "1–2 min",
    momentos: ["vestirse", "baño", "calle"],
    conQuien: "mama",
    progresion: "P1",
    origen: {
      de: "mirada",
      refs: [
        "mirada:la-cancion-de-siempre-al-vestirlo",
        "habla:modelado-vestirse",
        "habla:modelado-cancion-de-la-rutina",
      ],
    },
    fuente: "Stokes, 1977, J Appl Behav Anal · Childers, 2002, Dev Psychol",
  },
  {
    id: "la-locion-despues-del-bano",
    grupo: "comprender",
    prioridad: "normal",
    tecnica: "pausa-antes-de-lo-mejor",
    titulo: "La loción después del baño",
    tenALaMano: ["La loción, y él de frente, ya seco."],
    haz: [
      "Ponte loción en las manos y frótalas: «¡frío, frío!».",
      "Hazlo dos veces seguidas, con las mismas palabras.",
      "A la tercera, manos en el aire, y espera tres segundos mirándolo.",
      "Cuando te mire, se ría o se acerque, sigue: «¡en la barriga!».",
      "Cuando se acabe: «se acabó la loción».",
    ],
    tuLinea: "«Loción… frío, frío…» (manos en el aire) «…¡en la barriga!»",
    esperaVer: "Que se adelante a la loción cuando oye «frío, frío», y que te mire en la pausa.",
    funcionoSi:
      "al oír «frío, frío» se prepara o se acerca antes de que lo toques, o te mira en la pausa para que sigas.",
    siNoPasa:
      "Si el baño ya es tenso, ese día solo baño. No alargues la pausa con él mojado y con frío. Sirve igual con la toalla.",
    duracion: "2–3 min",
    momentos: ["baño"],
    conQuien: "mama",
    progresion: "P1",
    origen: { de: "mirada", refs: ["mirada:la-locion-despues-del-bano"] },
    fuente: "Halle, 1981, J Appl Behav Anal · Childers, 2002, Dev Psychol",
  },
  {
    id: "su-cancion-con-hueco",
    grupo: "comprender",
    prioridad: "normal",
    tecnica: "canto-a-su-ritmo",
    titulo: "Su canción, con un hueco antes de lo mejor",
    tenALaMano: ["Una de las canciones que ya le gustan: esa, no una nueva."],
    haz: [
      "Cántala una vez completa, de frente y a su altura.",
      "La segunda vez, detente justo antes de lo mejor —el «¡pum!», el «ruedan y ruedan»— con la boca abierta y cara de espera.",
      "Espera dos o tres segundos.",
      "Cuando te mire, haga el gesto o un sonido, sigue cantando.",
      "Si no llena el hueco, cántala completa y sigue: el hueco queda sembrado.",
    ],
    tuLinea: "«Los pollitos dicen…» (silencio, cara de espera) «…¡pío, pío, pío!»",
    esperaVer:
      "Que llene el hueco con la mirada, un gesto o un sonido; a veces, con la vocal de la palabra que falta.",
    funcionoSi:
      "llena el hueco de la canción con algo suyo: la mirada, el gesto, un sonido o un pedacito de la palabra.",
    siNoPasa:
      "No pruebes con una canción nueva. Y no sostengas el silencio hasta que se aburra: tres segundos y sigues.",
    duracion: "2–3 min",
    momentos: ["juego", "dormir", "calle"],
    conQuien: "mama",
    progresion: "P1",
    origen: {
      de: "mirada",
      refs: ["mirada:su-cancion-con-hueco", "habla:espera-pausa-canciones"],
    },
    fuente: "Kim, 2008 · Halle, 1981, J Appl Behav Anal",
  },
  {
    id: "ponle-nombre-a-lo-que-siente",
    grupo: "comprender",
    prioridad: "normal",
    tecnica: "su-palabra-mas-una",
    titulo: "Ponle nombre a lo que siente",
    tenALaMano: ["Nada: los momentos fuertes del día (alegría, susto, rabia, cosquillas)."],
    haz: [
      "Cuando sienta algo fuerte, acércate y míralo.",
      "Ponle una sola palabra, clara, con tu cara: «¡susto!», «¡qué risa!», «¡rabia!».",
      "Acompáñala con tu abrazo o tu mano, sin explicaciones largas.",
      "Si él hace un sonido, devuélveselo con la palabra: «¡aaay! ¡susto!».",
    ],
    tuLinea: "«¡Susto!… Ya pasó.»",
    esperaVer:
      "Que se quede cerca de ti mientras nombras lo que siente, y que a veces repita tu sonido o tu cara.",
    funcionoSi:
      "te busca o te mira cuando siente algo fuerte, o hace el sonido o la cara que acompañan tu palabra.",
    siNoPasa:
      "Si está muy alterado, primero la calma, después la palabra. Una palabra, no un discurso. Nunca «no llores» ni «no pasó nada».",
    duracion: "1 min",
    momentos: ["juego", "baño", "transiciones"],
    conQuien: "mama",
    origen: { de: "habla", refs: ["habla:recast-nombra-lo-que-siente"] },
    fuente: "Heidlage, 2020, Early Child Res Q · Tomasello, 1986, Child Dev",
  },
  {
    id: "acciones-en-tres-palabras",
    grupo: "comprender",
    prioridad: "normal",
    tecnica: "ahora-yo-ahora-tu",
    titulo: "Acciones con objetos, en tres palabras",
    tenALaMano: [
      "Dos objetos iguales (dos carros, dos cucharas, dos tambores), en el piso, a su altura, y un sonido para cada uno.",
    ],
    haz: [
      "Toma uno y haz una sola acción con su sonido y su frase: «el carro corre… ¡brrrum!».",
      "Deja el otro a su alcance y espera unos segundos.",
      "Si lo imita, di la frase otra vez sobre lo que hace él.",
      "Si no, repite la acción con la frase, sin llevarle la mano.",
      "Cambia de acción solo cuando esa ya salga: «el carro duerme», «la cuchara come… ¡ñam!».",
    ],
    tuLinea: "«El carro corre… ¡brrrum!»",
    esperaVer: "Primero copia el sonido; después la acción; luego hace la acción cuando oye la frase.",
    funcionoSi:
      "con el carro en la mano y tú sin moverte, al oír «el carro corre» lo hace correr, y al oír «el carro duerme» lo acuesta.",
    siNoPasa:
      "Demasiadas cosas a la vista: deja solo los dos objetos iguales, en el piso. Empieza por acciones grandes que ya copia, como marchar el muñeco.",
    duracion: "3–5 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "P2",
    origen: { de: "nueva", refs: ["anexo:C-C5"] },
    fuente: "Childers, 2002, Dev Psychol · Yu, 2012",
  },
  {
    id: "corre-que-te-atrapo-con-palabras",
    grupo: "comprender",
    prioridad: "normal",
    tecnica: "pausa-antes-de-lo-mejor",
    titulo: "Corre que te atrapo, con palabras",
    tenALaMano: ["El pasillo, y el hermano si quiere jugar."],
    haz: [
      "Arranca el juego que ya funciona.",
      "Mete cuatro palabras fijas, siempre las mismas: «¡ya!» (arranca), «¡para!» (todos quietos), «¡despacio!» (cámara lenta), «¡otra vez!».",
      "Al principio, cada palabra va con su gesto, y tú lo haces al decirla.",
      "Después, di la palabra y quédate sin moverte un segundo antes de hacerlo.",
      "Si el hermano juega, usa las mismas cuatro palabras.",
    ],
    tuLinea: "«¡Ya!…» (corren) «…¡para!» (todos quietos) «…¡otra vez!»",
    esperaVer: "Risa; al principio copia tu cuerpo; después se mueve por la palabra.",
    funcionoSi:
      "se queda quieto al oír «¡para!» antes que tú, o arranca con «¡ya!» mientras tú sigues sin moverte.",
    siNoPasa: "Demasiadas palabras, o cambiaron: quédate solo con «¡ya!» y «¡para!».",
    duracion: "2–3 min",
    momentos: ["juego"],
    conQuien: "mama",
    progresion: "P2",
    origen: { de: "nueva", refs: ["anexo:C-C8"] },
    fuente: "Wetherby, 2014, Pediatrics · Carter, 2011, J Child Psychol Psychiatry",
  },
];

/**
 * Las cápsulas de la app que el mapa deja FUERA del documento. Siguen intactas en la app; aquí
 * solo queda la razón. Con las `refs` de FICHAS, cada una de las 74 aparece exactamente una vez
 * (tests/unit/fichas.test.ts lo exige).
 *   necesita-la-app   → su gracia es el juego de voz o la pantalla, que el documento no tiene.
 *   etapa-siguiente   → piden juntar dos palabras; vuelven cuando esa etapa llegue.
 *   va-a-que-no-hacer → su idea es una regla, y quedó en el bloque «Qué no hacer».
 */
export const CAEN_DEL_DOCUMENTO: {
  id: string;
  razon: "necesita-la-app" | "etapa-siguiente" | "va-a-que-no-hacer";
}[] = [
  { id: "interes-voz-mueve", razon: "necesita-la-app" },
  { id: "interes-co-uso", razon: "necesita-la-app" },
  { id: "sonidos-cualquier-sonido-cuenta", razon: "necesita-la-app" },
  { id: "interes-cohete-de-la-voz", razon: "necesita-la-app" },
  { id: "interes-palabra-y-objeto", razon: "necesita-la-app" },
  { id: "frases-dos-palabras-utiles", razon: "etapa-siguiente" },
  { id: "frases-el-hueco-de-la-segunda", razon: "etapa-siguiente" },
  { id: "frases-narra-con-dos", razon: "etapa-siguiente" },
  { id: "frases-cuenta-cuentos-con-huecos", razon: "etapa-siguiente" },
  { id: "focalizada-sin-examen", razon: "va-a-que-no-hacer" },
  { id: "focalizada-no-preguntes-nombra", razon: "va-a-que-no-hacer" },
];
